"""create tables

Revision ID: 5bc3461acbf9
Revises: 
Create Date: 2026-05-03 10:38:07.002432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '5bc3461acbf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_data',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_hero_data_name'), 'hero_data', ['name'], unique=False)
    op.create_table('team_data',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('headquarters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_team_data_name'), 'team_data', ['name'], unique=False)
    op.create_table('hero_team_link',
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['hero_data.id_'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team_data.id_'], ),
    sa.PrimaryKeyConstraint('hero_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_team_link')
    op.drop_index(op.f('ix_team_data_name'), table_name='team_data')
    op.drop_table('team_data')
    op.drop_index(op.f('ix_hero_data_name'), table_name='hero_data')
    op.drop_table('hero_data')
    # ### end Alembic commands ###
